# Generated by Django 3.0.3 on 2020-02-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='essay',
            name='score',
        ),
        migrations.AddField(
            model_name='essay',
            name='score_container',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evaluator.Score'),
            preserve_default=False,
        ),
    ]
