# Generated by Django 3.0.3 on 2020-02-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_auto_20200228_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='model_pred',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
