# Generated by Django 3.0.3 on 2020-02-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_score_model_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='high_sample',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='low_sample',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='med_sample',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
