# Generated by Django 3.0.3 on 2020-02-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_auto_20200228_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='high_sample',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='low_sample',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='med_sample',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_desc',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.TextField(max_length=100000),
        ),
    ]
